#! /usr/bin/env bash

# Helper script for gitleaks to be used as a pre-commit hook.

red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
normal='\033[0m'

gitleaksEnabled=$(git config --bool hooks.gitleaks)

if [[ -z "$gitleaksEnabled" ]] || [[ "$gitleaksEnabled" = "true" ]]; then
	if [[ -x "$(command -v gitleaks)" ]]; then
		if ! gitleaks protect -v --staged; then
			echo
			echo -e "${red}Warning: gitleaks has detected sensitive information in your changes.${normal}"
			echo
			echo -e "For more information, visit https://path.app.corpintra.net/secret-scanning-with-gitleaks/"
			exit 1
		else
			echo
			echo -e "${green}gitleaks has scanned the repository and found no sensitive information.${normal}"
			echo
			echo -e "For more information, visit https://path.app.corpintra.net/secret-scanning-with-gitleaks/"
		fi
	else
		echo -e "${red}gitleaks is not installed but enabled. Cannot scan the repository. Please install gitleaks.${normal}"
		echo
		echo -e "For more information, visit https://path.app.corpintra.net/secret-scanning-with-gitleaks/"
		exit 1
	fi
else
	echo -e "${yellow}gitleaks pre-commit disabled. Will not scan the repository."
	echo -e "Enable the gitleaks pre-commit hook by running: git config hooks.gitleaks true${normal}"
	echo
	echo -e "For more information, visit https://path.app.corpintra.net/secret-scanning-with-gitleaks/"
fi
